"""Prompt builder service for Version 2."""

from __future__ import annotations

from pathlib import Path


class PromptBuilderError(RuntimeError):
    """Raised when a prompt cannot be built from the template."""


class PromptBuilder:
    """
    Build an LLM prompt using the complete relational schema
    and the user's natural-language question.

    The schema may contain:
    - Multiple tables
    - Columns and data types
    - Primary keys
    - Foreign keys
    - Detected relationships
    """

    SCHEMA_PLACEHOLDER = "{{SCHEMA}}"
    QUESTION_PLACEHOLDER = "{{QUESTION}}"

    def __init__(
        self,
        template_path: str | Path | None = None,
    ) -> None:
        self.template_path = Path(
            template_path
            or Path(__file__).resolve().parents[1]
            / "prompts"
            / "text_to_sql.txt"
        )

    def build_prompt(
        self,
        schema_text: str,
        question: str,
    ) -> str:
        """
        Build the final Text-to-SQL prompt.

        Args:
            schema_text:
                Complete relational schema generated by SchemaManager
                and RelationshipDetector.

            question:
                User's natural-language question.

        Returns:
            Fully rendered prompt ready for the LLM.

        Raises:
            PromptBuilderError:
                If schema, question, template, or placeholders are invalid.
        """

        schema = self._validate_input(
            schema_text,
            "A valid schema is required to build the prompt.",
        )

        user_question = self._validate_input(
            question,
            "A valid question is required to build the prompt.",
        )

        template = self._load_template()

        self._validate_template(template)

        prompt = template.replace(
            self.SCHEMA_PLACEHOLDER,
            schema,
        )

        prompt = prompt.replace(
            self.QUESTION_PLACEHOLDER,
            user_question,
        )

        return prompt

    @staticmethod
    def _validate_input(
        value: str,
        error_message: str,
    ) -> str:
        """Validate and normalize a required text input."""

        if value is None or not str(value).strip():
            raise PromptBuilderError(error_message)

        return str(value).strip()

    def _load_template(self) -> str:
        """Read the prompt template from disk."""

        try:
            return self.template_path.read_text(
                encoding="utf-8"
            )

        except FileNotFoundError as exc:
            raise PromptBuilderError(
                f"Prompt template not found: {self.template_path}"
            ) from exc

        except OSError as exc:
            raise PromptBuilderError(
                f"Unable to read the prompt template: {exc}"
            ) from exc

    def _validate_template(self, template: str) -> None:
        """
        Ensure the template contains the placeholders
        required by the PromptBuilder.
        """

        if self.SCHEMA_PLACEHOLDER not in template:
            raise PromptBuilderError(
                f"Prompt template is missing "
                f"{self.SCHEMA_PLACEHOLDER} placeholder."
            )

        if self.QUESTION_PLACEHOLDER not in template:
            raise PromptBuilderError(
                f"Prompt template is missing "
                f"{self.QUESTION_PLACEHOLDER} placeholder."
            )